# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [ ]:
import numpy as np

In [ ]:
data = np.random.randint(0, 20, size = (4, 7))

In [ ]:
data/np.linalg.norm(data)

array([[0.18006192, 0.        , 0.18006192, 0.0491078 , 0.09821559,
        0.26190824, 0.27827751],
       [0.03273853, 0.31101604, 0.06547706, 0.31101604, 0.        ,
        0.14732339, 0.31101604],
       [0.09821559, 0.22916971, 0.24553898, 0.18006192, 0.08184633,
        0.27827751, 0.13095412],
       [0.03273853, 0.14732339, 0.14732339, 0.26190824, 0.08184633,
        0.19643118, 0.21280045]])

2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [ ]:
a = np.random.randint(0, 10, size = (8, 10))
a

array([[7, 1, 2, 6, 2, 3, 3, 1, 7, 9],
       [5, 3, 7, 7, 8, 2, 1, 6, 0, 3],
       [2, 8, 1, 8, 2, 8, 5, 9, 1, 2],
       [5, 2, 6, 7, 2, 1, 3, 3, 9, 0],
       [7, 2, 7, 6, 4, 9, 3, 5, 1, 5],
       [2, 2, 5, 0, 6, 4, 1, 0, 3, 9],
       [9, 5, 9, 8, 0, 7, 8, 2, 6, 7],
       [2, 5, 4, 3, 5, 5, 3, 1, 9, 7]])

In [ ]:
k = sum(a[0])
for i in range(1, 8):
    if k > sum(a[i]):
      k = sum(a[i])
      count = i
print(k)
print(a[i])

32
[2 5 4 3 5 5 3 1 9 7]


3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [ ]:
import matplotlib.pyplot as pl
from mpl_toolkits.mplot3d import Axes3D

4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [ ]:
mas = np.loadtxt("minutes_n_ingredients.csv", delimiter=",", dtype = int)
print(mas[:5])

ValueError: ignored

2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [ ]:
from prettytable import PrettyTable
x = []
y = []
for i in mas:
    x.append(i[1])
    y.append(i[2])

t = PrettyTable(['', 'Среднее значение', 'Минимум', 'Максимум', 'Медиана'])
t.add_row(['Второй столбец', np.mean(mas, axis=0)[1], np.min(mas, axis=0)[1], np.max(mas, axis=0)[1], np.median(x)])
t.add_row(['Третий столбец', np.mean(mas, axis=0)[2], np.min(mas, axis=0)[2], np.max(mas, axis=0)[2], np.median(y)])
print(t)

+----------------+------------------+---------+------------+---------+
|                | Среднее значение | Минимум |  Максимум  | Медиана |
+----------------+------------------+---------+------------+---------+
| Второй столбец |   21601.00169    |    0    | 2147483647 |   40.0  |
| Третий столбец |     9.05528      |    1    |     39     |   9.0   |
+----------------+------------------+---------+------------+---------+


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [ ]:
np.quantile(mas, 0.75, axis=0)[1]

65.0

4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [ ]:
count = 0
for i in range(len(x)):
  if x[i] == 0:
    count = count + 1
    mas[i][1] = 1
print(count) 



479


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [ ]:
len(np.unique(mas))

100544

6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [ ]:
print(np.unique(y))
len(np.unique(y))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 37 39]


37

7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [ ]:
z = [mas[i] for i in range(len(mas)) if y[i] <= 5]
np.array(z)

array([[446597,     15,      5],
       [204134,      5,      3],
       [ 25623,      6,      4],
       ...,
       [ 52088,     60,      5],
       [128811,     15,      4],
       [370915,      5,      4]])

8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [ ]:
min_1 = [y[i] for i in range(len(x)) if x[i] == 1]
print(np.mean(min_1), max(min_1))


4.286919831223629 23


9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [ ]:
mas_sort_100 = mas[mas[:, 1].argsort()[:100]]
np.mean(mas_sort_100, axis=0)[2]

7.81

10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [ ]:
mas[np.random.choice(mas.shape[0], 10, replace=False), :]

array([[173259,      5,      6],
       [325286,     20,      6],
       [447255,     50,      9],
       [254267,     42,      9],
       [485110,     75,     15],
       [ 90486,    120,     11],
       [325965,     15,      9],
       [188902,     40,     13],
       [308423,     18,      4],
       [ 49451,      3,      4]])

11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [ ]:
average_ = np.mean(mas, axis=0)[2]
mas_percent = [mas[i][2] for i in range(len(x)) if mas[i][2] < average_]
print("Процент рецептов, кол-во ингредиентов в которых меньше среднего:", len(mas_percent) / len(mas) * 100)

Процент рецептов, кол-во ингредиентов в которых меньше среднего: 58.802


12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [ ]:
new_column = []
for i in range(len(mas)):
  if mas[i][1] <= 20 and mas[i][2] <= 5:
    new_column.append(1)
  else:
    new_column.append(0)
new_mas = np.insert(mas, 3, new_column, axis= 1)
print(new_mas)


[[127244     60     16      0]
 [ 23891     25      7      0]
 [ 94746     10      6      0]
 ...
 [498432     65     15      0]
 [370915      5      4      1]
 [ 81993    140     14      0]]


13. Выведите процент "простых" рецептов в датасете

In [ ]:
count = 0
for i in range(len(new_mas)):
  if new_mas[i][3] == 1:
    count = count + 1
print("Процент 'простых' рецептов:", count / len(mas) * 100)

Процент 'простых' рецептов: 9.552


14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [ ]:
new_column_type = []
for i in range(len(mas)):
  if mas[i][1] < 10:
    new_column_type.append(1)
  elif 10 <= mas[i][1] < 20:
    new_column_type.append(1)
  else:
    new_column_type.append(3)
new_mas_type = np.insert(mas, 0, new_column_type, axis= 1)
print(np.reshape(new_mas_type, (-1, 2, 2)))



[[[     3 127244]
  [    60     16]]

 [[     3  23891]
  [    25      7]]

 [[     1  94746]
  [    10      6]]

 ...

 [[     3 498432]
  [    65     15]]

 [[     1 370915]
  [     5      4]]

 [[     3  81993]
  [   140     14]]]
